### ISSUE TITLE
[BUG] Import/export whole database on collection edit view

### ISSUE THREAD

**Issue by r0emek** [Baboo7/strapi-plugin-import-export-entries#122]
Buttons export/import on collection add/edit view open whole database flow.

**To Reproduce**

1. Go to any collection type
2. enter existing one or add new to collection to ender edit view
3. click export or import button

**Expected behavior**
Export/import for specific collection type starts (filtered collection)

**Screenshots**
Collection:
![image](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/10465014/77f359d8-921c-4537-a13d-6f288b8f3af5)

Single:
![image](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/10465014/1fdddc6f-ee83-4446-8788-72c8ba438d42)

**Additional context**
It works correctly for single types

**Comment by Baboo7** [comment]
@r0emek this is fixed in version `v1.19.3` (#124)

**Comment by UbikK** [comment]
Hi! I still have this problem in the current version... Reading the PR, I'd say it's because of the regex used for parsing the pathname: it uses collectionType instead of collection-types and the same is true for singleType instead of single-types.

**Comment by barrett-rob** [comment]
Hello. We are having this issue with version

```json
    "@strapi/strapi": "4.17.0",
    "strapi-plugin-import-export-entries": "^1.23.1",
```
