### ISSUE TITLE
[BUG] CSV objects

### ISSUE THREAD

**Issue by rallisf1** [Baboo7/strapi-plugin-import-export-entries#4]
**Describe the bug**
When exporting a collection to CSV the fields that contain objects show `[object Object]`

**To Reproduce**
1. Go to any collection with entires in Content Manager
2. Click on Export, select CSV and Fetch Data

**Expected behavior**
Usually you only need the id of those fields as you will be importing them separetely. If you believe you should import the relations in 1 step then just json_encode the objects in the csv field

**Screenshots**
This is a demo output of a single country
```csv
"id","name","createdAt","updatedAt","locale","code","enabled","in_eu","phone_code","taxes","createdBy","updatedBy","localizations"
"1","Afghanistan","2022-06-04T17:55:04.734Z","2022-06-04T17:57:04.808Z","en","AF","false","false","93","","[object Object]","[object Object]","[object Object]"
```

**Additional context**
Haven't tried importing yet but I guess it will break as I am using 2 languages and I can't really import both. The final intention with this is to be able to migrate data from one installation to another via export/import.

**Comment by rallisf1** [comment]
I just saw you already pushed a fixed for this today. Just upgraded and doing tests. Hold that thought...

**Comment by rallisf1** [comment]
Ok, export works, although I don't agree with exporting whole objects of relations/owner/translations. But import is not working. When I leave the csv headers it doesn't import anything and without the headers it imports half the fields.

**Comment by Baboo7** [comment]
Stringifying objects before exporting them as CSV is a quick fix to at least get the data. I'm currently working on an option to flatten the keys of the exported entries.

About the import, a header is required even if it's not explicitly mentioned yet.
I agree that the import feature needs some love.  

Before importing the `countries`, do you first plan to export/import the `localizations` or do you expect that importing the `countries` will create the `localizations` on the fly for you?

**Comment by rallisf1** [comment]
> I agree that the import feature needs some love.

No worries, I imported directly to the db for now. Still experimenting with strapi as a whole so not in any hurry.

> Before importing the countries, do you first plan to export/import the localizations or do you expect that importing the countries will create the localizations on the fly for you?

Unless you know of a way to link translations after the fact, I guess create them on the fly.

**Comment by Baboo7** [comment]
I just pushed a fix with version `1.3.6`, import should be working now. Relations are updated or created in the fly if missing in db.
I added an [example on how import behaves](https://github.com/Baboo7/strapi-plugin-import-export-entries#usage) in the doc.

**Comment by victazzz** [comment]
Hello,

As for me, the import option still doesn't quite work.

I am using a file that I previously exported, I set different id's and the import goes through, but unfortunately the relationships as well as the record names themselves are not imported. 

Maybe I am doing something wrong, but I have tried several ways and read the docs you uploaded.

@Baboo7

**Comment by Baboo7** [comment]
Have you updated to latest version (`1.4.1`)? If you're just moving some data from one database to another, you don't need to update ids manually. Entries will be created/updated according to imported data and relations should be kept as is.

Is the import partially working? Or is it failing completely?
Also, can you share the file you're trying to import if there is no confidential data?

**Comment by victazzz** [comment]
Yes, I have the latest version and the upload is successful, only specific fields such as name or relationship are not imported via csv. As for the json import, it is ok and seems to work correctly.

I am uploading the sample csv data for import below.


`id;name;products;createdAt;updatedAt;publishedAt;createdBy;updatedBy
1;Silmkafaka;"[{""id"":1,""name"":""CLEAN&COLOR"",""modalName"":""CLEAN&COLOR"",""modalDescription"":""dawdwad"",""createdAt"":""2022-05-25T21:39:43.524Z"",""updatedAt"":""2022-06-12T18:48:54.245Z"",""publishedAt"":""2022-06-12T17:56:03.295Z"",""locale"":""en""}]";2022-06-12T18:37:59.914Z;2022-06-12T18:48:54.249Z;2022-06-12T18:48:19.801Z;"{""id"":1,""firstname"":""test"",""lastname"":""test"",""username"":null,""email"":""test@test.pl"",""password"":""$2a$10$schaV/qfTKo.HOZ2j183YeFhp2CqTY2vyyAiPQmenlCdiral2F6Aa"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-05-25T21:25:33.552Z"",""updatedAt"":""2022-05-25T21:27:46.614Z""}";"{""id"":1,""firstname"":""test"",""lastname"":""test"",""username"":null,""email"":""test@test.pl"",""password"":""$2a$10$schaV/qfTKo.HOZ2j183YeFhp2CqTY2vyyAiPQmenlCdiral2F6Aa"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-05-25T21:25:33.552Z"",""updatedAt"":""2022-05-25T21:27:46.614Z""}"
1;Dawdawdwadhhuhuu;[];2022-06-12T18:37:59.914Z;2022-06-12T18:48:54.254Z;2022-06-12T18:48:08.174Z;"{""id"":1,""firstname"":""test"",""lastname"":""test"",""username"":null,""email"":""test@test.pl"",""password"":""$2a$10$schaV/qfTKo.HOZ2j183YeFhp2CqTY2vyyAiPQmenlCdiral2F6Aa"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-05-25T21:25:33.552Z"",""updatedAt"":""2022-05-25T21:27:46.614Z""}";"{""id"":1,""firstname"":""test"",""lastname"":""test"",""username"":null,""email"":""test@test.pl"",""password"":""$2a$10$schaV/qfTKo.HOZ2j183YeFhp2CqTY2vyyAiPQmenlCdiral2F6Aa"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-05-25T21:25:33.552Z"",""updatedAt"":""2022-05-25T21:27:46.614Z""}"`

**Comment by victazzz** [comment]
no errors in the console, no error in the network either, the plugin says the import was successful but the names are not imported.

![image](https://user-images.githubusercontent.com/24989821/173910705-8b362c3b-1764-46a5-8083-5e1f5415148b.png)

![image](https://user-images.githubusercontent.com/24989821/173910833-be54f189-810e-4bd0-9843-b9e70b381fa4.png)

**Comment by Baboo7** [comment]
@victazzz some progress has been made over the past weeks. Do you still face the issue with latest version `1.6.1`?

**Comment by victazzz** [comment]
@Baboo7  
![image](https://user-images.githubusercontent.com/24989821/177217701-8074c8ac-ba1f-41a6-b7a5-daf036f1a1d1.png)

 keep having problems whether I try to import with id or full objects, it doesn't load specific fields and creates strange id's

**Comment by victazzz** [comment]
any update @Baboo7 ?

**Comment by victazzz** [comment]
@Baboo7, yes I have exported data with and without id and neither of these options creates the records correctly in the database the new id comes in but it does not fill them with the data from the csv I keep getting this error.

`Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at /Users/me/Projects/myproject/node_modules/strapi-plugin-import-export-entries/server/services/import/utils/parsers.js:14:28 at Array.map (<anonymous>) at parseCsv (/Users/me/Projects/myproject/node_modules/strapi-plugin-import-export-entries/server/services/import/utils/parsers.js:11:1`

**Comment by Baboo7** [comment]
Do you process the csv before importing it?

**Comment by victazzz** [comment]
yes

**Comment by Baboo7** [comment]
Usually the error `Unexpected token u in JSON` is thrown when trying to JSON.parse an `undefined`. I checked the json above but could not find any potential `undefined` values. May be the way you process the csv introduces an `undefined` somewhere?

As a side note, I noticed in the json above that the 2 entries have the same id. It shouldn't be an issue when importing data but it may produce unexpected results

**Comment by victazzz** [comment]
I cleaned the database, created new records by hand, exported the collection and changed the data such as name id etc. in the export.

I changed the data in the export such as the name id etc. and the same thing happened: it still creates a record with a strange id without any data in the fields. 

I have tried the version with and without the relationship id. 

@Baboo7

**Comment by victazzz** [comment]
yes and now sometimes an upload will be made but other relationships are lost or sometimes these relationships become detached. For example, I have a collection of product categories and colours and if I want to import some colours which have relations to the category and the product, the previous ones get lost.

@Baboo7

**Comment by Baboo7** [comment]
Would you mind sharing the complete involved database schema with the imported csv?

**Comment by victazzz** [comment]
@Baboo7 okay ok I will prepare it in a couple of hours

**Comment by victazzz** [comment]
shops

`{
  "kind": "collectionType",
  "collectionName": "shops",
  "info": {
    "singularName": "shop",
    "pluralName": "shops",
    "displayName": "Shop",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "unique": true,
      "required": true
    },
    "products": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::product.product",
      "inversedBy": "shops"
    }
  }
}
`
products
`{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "singularName": "product",
    "pluralName": "products",
    "displayName": "Product",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "required": true,
      "unique": true
    },
    "modalName": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "modalDescription": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "text"
    },
    "modalLogo": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "images": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "shops": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::shop.shop",
      "mappedBy": "products"
    },
    "colors": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::color.color",
      "inversedBy": "products"
    },
    "slug": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "uid",
      "targetField": "name",
      "required": false
    },
    "categories": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::category.category",
      "mappedBy": "product"
    },
    "useColorImage": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "boolean",
      "default": false
    },
    "colorImage": {
      "allowedTypes": [
        "images"
      ],
      "type": "media",
      "multiple": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    }
  }
}
`
colors
`{
  "kind": "collectionType",
  "collectionName": "colors",
  "info": {
    "singularName": "color",
    "pluralName": "colors",
    "displayName": "Color",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "category": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::category.category",
      "inversedBy": "colors"
    },
    "hex": {
      "type": "string"
    },
    "position": {
      "type": "integer"
    },
    "textWhite": {
      "type": "boolean",
      "default": false
    },
    "buttonInverse": {
      "type": "boolean",
      "default": false
    },
    "products": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::product.product",
      "mappedBy": "colors"
    },
    "image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "links": {
      "type": "component",
      "repeatable": true,
      "component": "link.links"
    },
    "number": {
      "type": "string",
      "required": false,
      "unique": true
    }
  }
}
`
category
`{
  "kind": "collectionType",
  "collectionName": "categories",
  "info": {
    "singularName": "category",
    "pluralName": "categories",
    "displayName": "Category",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "hex": {
      "type": "string",
      "customFieldConfig": {
        "fieldRenderer": "colorpicker"
      }
    },
    "colors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::color.color",
      "mappedBy": "category"
    },
    "product": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::product.product",
      "inversedBy": "categories"
    }
  }
}
`


csv 


`"id","name","category","hex","position","textWhite","buttonInverse","products","image","links","number","createdAt","updatedAt","publishedAt","createdBy","updatedBy"
"1","red","{""id"":1,""name"":""red"",""hex"":""#74757B"",""createdAt"":""2022-07-18T20:34:06.745Z"",""updatedAt"":""2022-07-18T20:43:00.410Z"",""colors"":[{""id"":1,""name"":""red"",""hex"":""#74757B"",""position"":1,""textWhite"":false,""buttonInverse"":false,""number"":null,""createdAt"":""2022-07-18T20:33:57.582Z"",""updatedAt"":""2022-07-18T20:42:43.392Z"",""publishedAt"":""2022-07-18T20:33:59.410Z""}],""product"":{""id"":1,""name"":""Dekoral Łazienka & Kuchnia"",""modalName"":""d"",""modalDescription"":""wda"",""slug"":""de"",""useColorImage"":false,""createdAt"":""2022-07-18T20:33:24.960Z"",""updatedAt"":""2022-07-18T20:42:43.392Z"",""publishedAt"":""2022-07-18T20:33:25.687Z"",""locale"":""en""},""createdBy"":{""id"":1,""firstname"":""adam"",""lastname"":""admin"",""username"":null,""email"":""admin@admin.pl"",""password"":""$2a$10$A.enhies8N58Yc9T0RC.p.r08sRi5KanPDbAIROmVDtPbFX./9xF6"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-07-18T20:32:54.837Z"",""updatedAt"":""2022-07-18T20:32:54.837Z""},""updatedBy"":{""id"":1,""firstname"":""adam"",""lastname"":""admin"",""username"":null,""email"":""admin@admin.pl"",""password"":""$2a$10$A.enhies8N58Yc9T0RC.p.r08sRi5KanPDbAIROmVDtPbFX./9xF6"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-07-18T20:32:54.837Z"",""updatedAt"":""2022-07-18T20:32:54.837Z""}}","#74757B","1","false","false","[]","null","[]","null","2022-07-18T20:33:57.582Z","2022-07-18T20:42:43.392Z","2022-07-18T20:33:59.410Z","{""id"":1,""firstname"":""adam"",""lastname"":""admin"",""username"":null,""email"":""admin@admin.pl"",""password"":""$2a$10$A.enhies8N58Yc9T0RC.p.r08sRi5KanPDbAIROmVDtPbFX./9xF6"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-07-18T20:32:54.837Z"",""updatedAt"":""2022-07-18T20:32:54.837Z"",""roles"":[{""id"":1,""name"":""Super Admin"",""code"":""strapi-super-admin"",""description"":""Super Admins can access and manage all features and settings."",""createdAt"":""2022-07-18T20:32:16.796Z"",""updatedAt"":""2022-07-18T20:32:16.796Z""}],""createdBy"":null,""updatedBy"":null}","{""id"":1,""firstname"":""adam"",""lastname"":""admin"",""username"":null,""email"":""admin@admin.pl"",""password"":""$2a$10$A.enhies8N58Yc9T0RC.p.r08sRi5KanPDbAIROmVDtPbFX./9xF6"",""resetPasswordToken"":null,""registrationToken"":null,""isActive"":true,""blocked"":false,""preferedLanguage"":null,""createdAt"":""2022-07-18T20:32:54.837Z"",""updatedAt"":""2022-07-18T20:32:54.837Z"",""roles"":[{""id"":1,""name"":""Super Admin"",""code"":""strapi-super-admin"",""description"":""Super Admins can access and manage all features and settings."",""createdAt"":""2022-07-18T20:32:16.796Z"",""updatedAt"":""2022-07-18T20:32:16.796Z""}],""createdBy"":null,""updatedBy"":null}"`

**Comment by victazzz** [comment]
@Baboo7  any update?

**Comment by Baboo7** [comment]
Not yet, but I will test asap and keep you up to date

**Comment by victazzz** [comment]
@Baboo7  and?

**Comment by Baboo7** [comment]
I have a lot going on these days and I'm doing my best to tackle issues. Since I'm alone working on the plugin, resources are limited and I need to prioritize issues by the number of people they impact. There are still some basic needs about import and export that needs to be addressed before I can fully focus on your issue. I can't give you a date of when I'll do so but I didn't forget you

**Comment by Baboo7** [comment]
Support of CSV is deprecated today and I don't plan to support it in a near future. I'm closing this issue for now
