### ISSUE TITLE
Import entries with multiple languages not work [BUG] 

### ISSUE THREAD

**Issue by hamed4000** [Baboo7/strapi-plugin-import-export-entries#64]
**Describe the bug**
```
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-i18n": "4.3.4",
    "@strapi/plugin-users-permissions": "4.3.4",
    "@strapi/strapi": "4.3.4",
    "better-sqlite3": "7.4.6",
    "pg": "^8.7.3",
    "slugify": "^1.6.5",
    "strapi-plugin-config-sync": "^1.0.3",
    "strapi-plugin-import-export-entries": "^1.12.0"
  },
```
I create a multi-language single type schema, when I export/import with multiple languages, this plugin only imports in the default language,

**Comment by Baboo7** [comment]
Hey @hamed4000 , I just published version `1.16.0` where export/import of locales is supported for `JSON v2` format 🎉

**Comment by hamed4000** [comment]
It works fine for collection types but not for a single type, only the default language is imported.
Maybe I must update strapi too?
I'll test and let you know the result

**Comment by Baboo7** [comment]
I'll dig into that 👍

**Comment by hamed4000** [comment]
```
"dependencies": {
    "@strapi/plugin-i18n": "4.4.1",
    "@strapi/plugin-users-permissions": "4.4.1",
    "@strapi/strapi": "4.4.1",
    "pg": "8.6.0",
    "strapi-plugin-config-sync": "^1.0.4",
    "strapi-plugin-import-export-entries": "^1.16.0"
  },
```

My current single collection
![Screenshot_collection](https://user-images.githubusercontent.com/43178970/193785524-956306a2-81ec-4e30-9922-3424878d8851.jpg)

When I want to **export** that with json v2 format, I get this error. So I get cv
![sjs](https://user-images.githubusercontent.com/43178970/193796232-dc968e5e-34fe-4918-8e8d-9b99019f528c.png)


When I want to **import** from cv format, I get this error
![cv import](https://user-images.githubusercontent.com/43178970/193786346-1885fd8a-7b27-495d-9968-61051fd0a5d2.jpg)

**Comment by Baboo7** [comment]
Single types are not handled properly at the moment. Since a single type is an object instead of an array, the issue makes sense. This issue is now my priority

**Comment by Baboo7** [comment]
Hey @hamed4000, new version `1.16.1` is out and single types are supported and it should fix your issue. Feel free to give your feedback on the [Discord](https://discord.gg/dcqCAFFdP8) 😌

**Comment by mauriceljx** [comment]
I think this is a related issue. My import only works for the default language, which gives me the following error 
`[
	{
		"error": "insert into \"categories_issues_links\" (\"category_id\", \"issue_id\") values ($1, $2) - insert or update on table \"categories_issues_links\" violates foreign key constraint \"categories_issues_links_inv_fk\"",
		"data": {
			"id": 1,
			"title": "NFT",
			"createdAt": "2022-10-10T08:13:28.840Z",
			"updatedAt": "2022-10-12T10:41:26.668Z",
			"publishedAt": "2022-10-10T08:13:48.061Z",
			"locale": "en",
			"issues": [
				1
			],
			"createdBy": null,
			"updatedBy": null,
			"localizations": [
				3
			]
		}
	},
	{
		"error": "insert into \"categories_issues_links\" (\"category_id\", \"issue_id\") values ($1, $2), ($3, $4) - insert or update on table \"categories_issues_links\" violates foreign key constraint \"categories_issues_links_inv_fk\"",
		"data": {
			"id": 2,
			"title": "Payment",
			"createdAt": "2022-10-10T08:13:39.130Z",
			"updatedAt": "2022-10-12T10:41:26.676Z",
			"publishedAt": "2022-10-10T08:13:42.493Z",
			"locale": "en",
			"issues": [
				4,
				3
			],
			"createdBy": null,
			"updatedBy": null,
			"localizations": [
				5
			]
		}
	}
]`
However, if I import again, the second localization gets added successfully.

This is the 1-to-Many relationship: 
![image](https://user-images.githubusercontent.com/54699961/195322672-842b35f0-1419-4c92-9a77-dc8150f9feb3.png)

**Comment by Baboo7** [comment]
This is an issue that is broader since it concerns how entries depend on one another and the order they are imported in. I'm actually working on this broader one now which will solve your problem

**Comment by Baboo7** [comment]
@hamed4000 @mauriceljx I published version `1.16.2` which solves the issue. Feel free to tell me if it doesn't work as expected

**Comment by mauriceljx** [comment]
I'm still getting the same error `TypeError: entries is not iterable` as @hamed4000 when exporting Single Types with a component.

This is the structure:
![image](https://user-images.githubusercontent.com/54699961/195749998-f05ae8b1-ee91-4145-985a-9a3b815bb51b.png)

I also just updated to `1.16.2` and tested the import with multiple languages and now it's giving a different error with nothing imported as a result:
![image](https://user-images.githubusercontent.com/54699961/195750331-18e570b0-ce91-42df-8dd1-7b633da83e04.png)

**Comment by Baboo7** [comment]
@hamed4000 @mauriceljx I published version `1.17.0` that fixes export/import of single types with json v2 format
